# ---------------------------------------------------
# Pisces Default Configuration File
# ---------------------------------------------------
# This file provides default settings for Pisces.
# Users can override these defaults using:
# - PISCES_CONFIG environment variable
# - .piscesrc in the project directory
# - ~/.config/pisces/config.yaml
#
# Values in this file are safe defaults suitable for most environments.
# ---------------------------------------------------
physics:
  default_cosmology: 'Planck15' # The default cosmology to assume unless overridden.

logging:
  # Logging configuration settings. These are overridden
  # in library configurations and are only relevant as
  # fallback.
  main:
    # Settings for the main logger accessed in utilities.logging.
    level: INFO
    format: "[Pisces]-%(levelname)s: %(message)s"

sympy:
  skip_constant_checks: 5  # The number of operations in a sympy exp. before we no longer check for constant.
