# ================================================================ #
# Default FRONTEND configuration for Gadget-4 simulations.         #
# ================================================================ #
# This configuration file sets up the frontend parameters for running
# Gadget-4 simulations within the Pisces framework. It includes settings
# for simulation parameters, output options, and analysis routines.

# -------------------------- #
# Makefile Options           #
# -------------------------- #
# These are compile-time settings which are necessary to
# ensure self-consistent / valid configurations.
makefile:
  simulation_type: "3D"         # The type of simulation (e.g., "3D", "2D"). This is set automatically.
  number_of_particle_types: 6   # The number of particle types expected.
  nbits_id: 64                  # The number of bits used for particle IDs.

# -------------------------- #
# Physics Settings           #
# -------------------------- #
physics:
  cooling: false                 # Turn on cooling. Requires user to specify the electron_abundance.

# -------------------------- #
# Parameter File Options     #
# -------------------------- #
# These are runtime configuration settings which are necessary
# to ensure that the simulation is run in a self-consistent manner.
parameters:

  # The simulation box size. This should be provided in the
  # same units as the length units specified below.
  boxsize: 100.0

  # Unit support. Gadget-4 includes velocity, length, and mass
  # units. The time unit is derived from L/V.
  units:
    length: !unyt_unit "Mpc"            # Length unit
    mass: !unyt_unit "Msun"             # Mass unit
    velocity: !unyt_unit "km/s"         # Velocity unit

# -------------------------- #
# Model Parameters (default) #
# -------------------------- #
# Below is the default set of model configurations for
# mapping Pisces particle data properties to Gadget-4 particle types.
# The convention present here matches the standard convention for Pisces.
#
# Once initialized, the frontend will create a unique one of these
# for each model so that it can have specific settings.
model_template:
  ParticleType0:
    name: "gas"
    fields:
      Coordinates: "particle_position"
      Velocities: "particle_velocity"
      ParticleIDs: "particle_id"
      Masses: "particle_mass"
      InternalEnergy: "particle_internal_energy"
  ParticleType1:
    name: "dark_matter"
    fields:
      Coordinates: "particle_position"
      Velocities: "particle_velocity"
      ParticleIDs: "particle_id"
      Masses: "particle_mass"
  ParticleType2:
    name: "disk"
    fields:
      Coordinates: "particle_position"
      Velocities: "particle_velocity"
      ParticleIDs: "particle_id"
      Masses: "particle_mass"
  ParticleType3:
    name: "bulge"
    fields:
      Coordinates: "particle_position"
      Velocities: "particle_velocity"
      ParticleIDs: "particle_id"
      Masses: "particle_mass"
  ParticleType4:
    name: "stars"
    fields:
      Coordinates: "particle_position"
      Velocities: "particle_velocity"
      ParticleIDs: "particle_id"
      Masses: "particle_mass"
  ParticleType5:
    name: "boundary"
    fields:
      Coordinates: "particle_position"
      Velocities: "particle_velocity"
      ParticleIDs: "particle_id"
      Masses: "particle_mass"

# Model configurations which are filled dynamically
# when initialized:
models:
